SELECT `AUTO_INCREMENT`
FROM  INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'testHibernate'
AND   TABLE_NAME   = 'torneo';




DROP PROCEDURE IF EXISTS cleanDb;

DELIMITER //

CREATE PROCEDURE cleanDb ()
BEGIN
	DELETE FROM TORNEO_JUGADOR;
	DELETE FROM TORNEO_PARTIDO;
	DELETE FROM TORNEO;
	DELETE FROM PARTIDO_JUGADOR;
	DELETE FROM PARTIDO;
	DELETE FROM JUGADOR;
END//

DELIMITER ;
	